#
#
# things you probably want to change
#
#

# no trailing slash
url: https://point-theme.netlify.app

# for header and meta tags
title: Point Theme ðŸŽ¯
description: description for search engines and social media cards

# set external to true if linking outside your website
# for internal, make sure to include preceding slash
nav-links:
  - name: Home
    url: /
    external: false
  - name: Blog
    url: /blog
    external: false
  - name: Contact
    url: /contact
    external: false
  - name: Search Engine
    url: https://duckduckgo.com
    external: true

# for the homepage image + big text next to it
greeting_image: /assets/me.jpg
# 100-200 characters recommended
greeting_text: Hey, I'm Point Theme! I'm a Jekyll theme for personal websites that are short & to the point. Fork it on Github, customize the styles and options, and enjoy!

# show blog post excerpts on blog page
show_excerpts: false
excerpt_word_count: 70

# long date: April 20, 1969
long_date: false
# short date: Apr â€˜69
short_date: true

#
#
# things you probably don't want to change
#
#
defaults:
  - # applies the default layout to all files in the project
    scope:
      path: ""
    values:
      layout: "default"
  - # sets is_post=true for all blog posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
permalink: /:title # so we have /about instead of /about.html, and /blog-post instead of /2019-11-22-blog-post.html
sass:
  style: compressed # compress the CSS file generated from the SCSS styles file
